version: "3.8"
services:

  filp:
    image: nginx:latest
    container_name: nginx_filp
    ports:
      - ${HTTP_PORT}
      - ${HTTPS_PORT}
    environment:
      - PHP_VERSION=${PHP_VERSION}
    links:
      - php_${PHP_VERSION}
    depends_on:
      - php_${PHP_VERSION}
      - phpmyadmin
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/conf.d/filp.conf:/etc/nginx/conf.d/20-backend.conf
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./public/:/application/filp.loc/public
    networks:
      default:
        aliases:
          - filp.loc

  php_8.0:
    container_name: php_filp
    build: ./docker/php_8.0
    env_file:
      - ./docker/project.env
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    depends_on:
      - mysql
    volumes:
      - ./:/application/filp.loc
      - ./docker/php_8.0/php-ini:/usr/local/etc/php/custom.d
    links:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_filp
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./docker/mysql-data/sql:/docker-entrypoint-initdb.d/
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=filp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_filp
    links:
      - mysql:db
    volumes:
      - ./docker/mysql-data/cfg/pma.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
